### ISSUE TITLE
Problem on Linux for "Match mode"

### ISSUE THREAD

**Issue by SSHad0w** [morpheuslord/AFrame#2]
I'm experiencing an issue while running `main.py` file.

```
$ python3 main.py 
  File "/home/sshad0w/Documents/launderer/QuadraInspect/main.py", line 47
    match mode:
          ^
SyntaxError: invalid syntax
```

Currently trying to find the patch.

**Comment by morpheuslord** [comment]
Yes Linux is not a fan of switch case statements working on it

**Comment by SSHad0w** [comment]
I've actually reproduced the bug on windows 10.

**Comment by morpheuslord** [comment]
Can you send a pic

**Comment by SSHad0w** [comment]
Is it okay if I just provide the code block?

```
  File "C:\Users\SSHad0w\OneDrive\Desktop\tool.py", line 49
    match mode:
          ^
SyntaxError: invalid syntax
[Finished in 96ms]
```
It's just the same error.

**Comment by SSHad0w** [comment]
## This only supports python3.10 and above.

After some research, I learned that match statements are only supported in python 3.10 and later, while python 3.9 and earlier don't have that feature. 

**Basically, if you want this to be backwards compatible, you'll need to change the `match [case]` statements to `if [case]` statements instead. You may also need to change the end of the statements to the `elif` format as well.**

I'm changing my version to see if this works, but I'm pretty sure that's the "bug". I'm using Python3.9, you must be using 3.10.

**Comment by morpheuslord** [comment]
Yup confirmed that the bug is related to the Python version, I will mention in the readme to use version `3.10` for compatibility

**Comment by morpheuslord** [comment]
> ## This only supports python3.10 and above.
> After some research, I learned that match statements are only supported in python 3.10 and later, while python 3.9 and earlier don't have that feature.
> 
> **Basically, if you want this to be backwards compatible, you'll need to change the `match [case]` statements to `if [case]` statements instead. You may also need to change the end of the statements to the `elif` format as well.**
> 
> I'm changing my version to see if this works, but I'm pretty sure that's the "bug". I'm using Python3.9, you must be using 3.10.


Yup confirmed that the bug is related to the Python version, I will mention in the readme to use version 3.10 for compatibility.

Check the README for the updates
