### ISSUE TITLE
could not find a version that satisfies the requirement apkutil==0.1.7 (from versions: none)

### ISSUE THREAD

**Issue by kuldeep3115** [morpheuslord/AFrame#3]
pip install -r /root/QuadraInspect/requirements.txt && python3 main.py 
Collecting apkleaks==2.6.1
  Using cached apkleaks-2.6.1-py3-none-any.whl (14 kB)

getting this error in Kali

ERROR: Could not find a version that satisfies the requirement apkutil==0.1.7 (from versions: none)
ERROR: No matching distribution found for apkutil==0.1.7

**Comment by morpheuslord** [comment]
The issue was that apkutils had to be installed manually within the system and not via PyPI.  I have updated the requirements.
you might have to run: `pip install --upgrade pip` to avoid such issues moving forward.
