### ISSUE TITLE
Attempts to run bat file on linux

### ISSUE THREAD

**Issue by nuschpl** [morpheuslord/AFrame#4]
The doc says it's multiplatform Linux/Windows/MAc but it seems only was tested on Windows. When I try:
`START mobfs`
it fails with:
```
  File "CUT/pentest/mobile/android/QuadraInspect/config/mobfs.py", line 7, in mobfs
    run('{}/run.bat 127.0.0.1:5000'.format(tdir))
  File "/usr/lib/python3.10/subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1845, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/CUT/pentest/mobile/android/QuadraInspect/tools/mobfs//run.bat 127.0.0.1:5000'
```

**Comment by morpheuslord** [comment]
Will correct it

**Comment by morpheuslord** [comment]
Try replacing the code in the `config\mobfs.py` file with this:
```python
import platform
from rich.pretty import pprint
from subprocess import run


def mobfs(rdir):
    osp = platform.system()
    match osp:
        case 'Darwin':
            pre = ""
            cmd = "run.sh"
        case 'Linux':
            pre = ""
            cmd = "run.sh"
        case 'Windows':
            pre = "bash"
            cmd = "run.bat"
    try:
        tdir = '{}/tools/mobfs/'.format(rdir)
        run('{a} {b}/{c}'.format(a=pre, b=tdir, c=cmd))
        pass
    except KeyboardInterrupt:
        pprint("Ending process ...")

```

**Comment by pullghjunkkk** [comment]
chikkachun@chikdeMBP QuadraInspect-1.1 % ./gradlew build

zsh: no such file or directory: ./gradlew
chikkachun@chikdeMBP QuadraInspect-1.1 % gradle build


FAILURE: Build failed with an exception.

* What went wrong:
Project directory '/Users/chikkachun/Documents/QuadraInspect-1.1' is not part of the build defined by settings file '/Users/chikkachun/settings.gradle'. If this is an unrelated build, it must have its own settings file.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 809ms
chikkachun@chikdeMBP QuadraInspect-1.1 % build.gradle
zsh: command not found: build.gradle
chikkachun@chikdeMBP QuadraInspect-1.1 % python3 main.py
Traceback (most recent call last):
  File "/Users/chikkachun/Documents/QuadraInspect-1.1/main.py", line 3, in <module>
    from pyfiglet import Figlet
ModuleNotFoundError: No module named 'pyfiglet'
chikkachun@chikdeMBP QuadraInspect-1.1 % START install_tools
zsh: command not found: START
chikkachun@chikdeMBP QuadraInspect-1.1 % python3.10 main.py


Traceback (most recent call last):
  File "/Users/chikkachun/Documents/QuadraInspect-1.1/main.py", line 3, in <module>
    from pyfiglet import Figlet
ModuleNotFoundError: No module named 'pyfiglet'
chikkachun@chikdeMBP QuadraInspect-1.1 % pip install -r requirements.txt && python3 main.py
WARNING: Ignoring invalid distribution -inja2 (/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages)
WARNING: Ignoring invalid distribution - (/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages)
WARNING: Ignoring invalid distribution -inja2 (/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages)
WARNING: Ignoring invalid distribution - (/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages)
Ignoring waitress: markers 'platform_system == "Windows"' don't match your environment
Collecting apkleaks==2.6.1
  Downloading apkleaks-2.6.1-py3-none-any.whl (14 kB)
ERROR: Could not find a version that satisfies the requirement apkutil==0.1.7 (from versions: none)
ERROR: No matching distribution found for apkutil==0.1.7
WARNING: Ignoring invalid distribution -inja2 (/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages)
WARNING: Ignoring invalid distribution - (/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages)
WARNING: Ignoring invalid distribution -inja2 (/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages)
WARNING: Ignoring invalid distribution - (/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages)
chikkachun@chikdeMBP QuadraInspect-1.1 % pip3.10 install -r requirements.txt && python3.10 main.py
Ignoring waitress: markers 'platform_system == "Windows"' don't match your environment
Collecting apkleaks==2.6.1
  Using cached apkleaks-2.6.1-py3-none-any.whl (14 kB)
ERROR: Could not find a version that satisfies the requirement apkutil==0.1.7 (from versions: none)
ERROR: No matching distribution found for apkutil==0.1.7

[notice] A new release of pip is available: 23.0 -> 23.1
[notice] To update, run: /usr/local/opt/python@3.10/bin/python3.10 -m pip install --upgrade pip
chikkachun@chikdeMBP QuadraInspect-1.1 % QuadraInspect Main>> : START install_tools
zsh: command not found: QuadraInspect
chikkachun@chikdeMBP QuadraInspect-1.1 %

**Comment by pullghjunkkk** [comment]
how to run???

**Comment by morpheuslord** [comment]
delete the main folder the tool is downloaded in and redownload it. I have done all the necessary changes

**Comment by morpheuslord** [comment]
> how to run???

and also i guess you are running python 3.10
