### ISSUE TITLE
E: Package 'libreadline-gplv2-dev' has no installation candidate

### ISSUE THREAD

**Issue by ppcs50** [morpheuslord/AFrame#5]
Hi, I'm trying to install pre-requisite and apt just gave me this error, not able to install all the libraries (Kali, 2022.4)
Once I ignored it and install everything other than that, but it failed and nothing worked.

**Comment by morpheuslord** [comment]
what python version are you using

**Comment by morpheuslord** [comment]
Maybe run this command and rerun the entire thing
```bash
sudo apt-get update && sudo apt-get upgrade -y && sudo apt-get install libreadline-dev -y
```

**Comment by ppcs50** [comment]
Thanks for your reply, I was using Python 3.10 but when you do SUDO UPDATE it will upgrade my python to 3.11, so it prevent me to install mobsf eventually... Ironic.
