### ISSUE TITLE
Recommend another toolbox

### ISSUE THREAD

**Issue by firmianay** [morpheuslord/AFrame#8]
Hello, maybe you will like this, another tool set that contains more tools and is more powerful.

https://github.com/VulnTotal-Team/Vehicle-Security-Toolkit/tree/main/apk_scan
https://github.com/VulnTotal-Team/Vehicle-Security-Toolkit/blob/main/apk-allinone.py

**Comment by morpheuslord** [comment]
Great suggestions, I will look into it. If you have a clue on how to integrate it fell free to create a PR on the additionals.py the installer script for new tools
